### ISSUE TITLE
Create Test for Employee

### ISSUE THREAD

**Issue by BurnsD** [BurnsD/laughing-computing-machine#3]
The first class is an Employee parent class with the following properties and methods:

name

id

email

getName()

getId()

getEmail()

getRole() // Returns 'Employee'

The other three classes will extend Employee.

**Comment by BurnsD** [comment]
Test code is written for the following functions:

getName()

getID()

getEmail()

getRole()

**Comment by BurnsD** [comment]
Currently receiving this error message:

FAIL _tests_/Employee.test.js
  ● Test suite failed to run

    TypeError: regex.exec is not a function

       5 |
       6 | // Create Employee Object
    >  7 | test('create employee object', () => {
         | ^
       8 |     const employee = new Employee()
       9 |
      10 |     expect(typeof(employee)).toBe('object');

      at test (node_modules/picomatch/lib/picomatch.js:140:21)
      at Object.<anonymous> (_tests_/Employee.test.js:7:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)

**Comment by BurnsD** [comment]
All Errors have been taken care of and all test now passed

The Following code has fixed the Employee.test.js:

const Employee = require('../lib/Employee');

// Create Employee Object
test('create employee object', () => {
    const employee = new Employee()

    expect(typeof(employee)).toBe('object');
});

// Make function to retrieve name and add to object
test('add name to employee object.', () => {
    const newName = "Name here";
    const employeeObject = new Employee(newName);
    expect(employeeObject.getName()).toBe(newName);
});

// Make function to retrieve employee ID
test('add id to employee object.', () => {
    const newID = "001";
    const employeeObject = new Employee("Name here", newID);
    expect(employeeObject.getId()).toBe(newID)
});

// Make function to retrieve E-mail
test('add email to employee object.', () => {
    const newEmail = "Test@notreal.com"
    const employeeObject = new Employee("Name here", "001", newEmail);
    expect(employeeObject.getEmail()).toBe(newEmail)
});

// Make function that returns Employee Object
test('Test role.', () => {
    const returnRole = "Employee";
    const employeeObject = new Employee("Name here", "001", "Test@notreal.com");
    expect(employeeObject.getRole()).toBe(returnRole);
});
